second attempt for first successful PR
karastoyanov/JSF-DIW pull request #16
Opened 2024-05-09 20:50 UTC by asenpetrov

2024-05-09 20:59 UTC, karastoyanov commented on Exercise01-Git/Asen-Petrov/helloWords-Asen-Petrov.js
Change the name of the file to **helloWorld**-Asen-Petrov.js

2024-05-09 21:00 UTC, karastoyanov commented on Exercise02-Basics/Asen-Petrov/basics01-004.js
Try to use the knowedge from Lesson03 and solve the exercise without arrays and loops.

2024-05-09 21:22 UTC, asenpetrov commented on Exercise01-Git/Asen-Petrov/helloWords-Asen-Petrov.js
file name changed

2024-05-09 21:22 UTC, asenpetrov commented on Exercise02-Basics/Asen-Petrov/basics01-004.js
Loops and arrays removed, variable set and printed separately.

2024-05-12 14:08 UTC, karastoyanov reviewed
Current progress has been approved.

2024-05-14 16:49 UTC, asenpetrov commented
Any pending actions on my end before being able to merge the PR?

2024-05-15 15:22 UTC, karastoyanov commented on Exercise02-Basics/Asen-Petrov/basics02-013.js
You can try and solve the task with ternary operators. The solution would be something like that:

```javascript
let result = (letter >= 'A' && letter <= 'Z') ? CHANGE THE UPPERCASE TO LOWERCASE EXPRESSION : (letter >= 'a' && letter <= 'z') ? CHANGE TO LOWERCASE TO UPPERCASE EXPRESSION : letter;
```

2024-05-15 15:23 UTC, karastoyanov commented on Exercise02-Basics/Asen-Petrov/basics02-014.js
You can try and solve the task with ternary operators. The solution would be something like that:

```javascript
let result = (letter >= 'A' && letter <= 'Z') ? CHANGE THE UPPERCASE TO LOWERCASE EXPRESSION : (letter >= 'a' && letter <= 'z') ? CHANGE TO LOWERCASE TO UPPERCASE EXPRESSION : letter;
```

2024-05-15 15:30 UTC, karastoyanov commented on Exercise02-Basics/Asen-Petrov/basics02-015.js
The code is fine, but you can try to solve it without if/else statements.

* First, we calculate the index of the ciphered letter by converting the given letter to its ASCII code, subtracting 65 to map 'A' to 0, adding the Cipher value, and then taking the modulo 26 to ensure it wraps around the alphabet.

* Then, we convert the calculated index back to a letter using String.fromCharCode and print it.

2024-05-15 15:31 UTC, karastoyanov requested changes
Take a look on the `BASIC02-014` and `BASIC02-015` tasks, the current solutions may be correct, but we can try to use the knowedge from the initial lessons.

2024-06-04 07:06 UTC, karastoyanov approved these changes

2024-06-04 07:06 UTC, karastoyanov commented
BASICS02-014 and BASICS02-015 fixed and commited in order to close the pill-request.

2024-06-04 07:07 UTC, merged