Hello world JS
karastoyanov/JSF-DIW pull request #31
Opened 2024-05-17 13:13 UTC by git-Ball

2024-05-17 20:18 UTC, karastoyanov requested changes
* Rename the file to `helloWorld-Georgi-Balabanov.js`

* The file should be placed in a `Exercise01-Git/Gergi-Balabanov` directory

* You don't need the `Exercise-demo` dir.

2024-05-31 04:46 UTC, karastoyanov commented on Exercise02-Basics/Georgi-Balabanov/BASICS02-014.js
You try to solve this one without using if-else statements, with ternary operators the solution would be something like that:

```js
let result = (letter >= 'A' && letter <= 'Z') ? CHANGE THE UPPERCASE TO LOWERCASE EXPRESSION : (letter >= 'a' && letter <= 'z') ? CHANGE TO LOWERCASE TO UPPERCASE EXPRESSION : letter;
```

2024-05-31 04:52 UTC, karastoyanov commented on Exercise03-DataTypes/Georgi-Balabanov/DTYPES01-003.js
> +console.log(fullRevName)
The separator should be `,`

2024-05-31 04:58 UTC, karastoyanov requested changes
Small corrections. Also, you may take a look on some of the solutions, where `;` after the print lines, like on [BASIC02-004.js](https://github.com/karastoyanov/JSF-DIW/blob/e73293ffcd536fb628ae728ee0d3625f38c66eb3/Exercise02-Basics/Georgi-Balabanov/BASICS02-004.js)

```js
let randomEmoji1 = '\u{1F703}';
let randomEmoji2 = '\u{1F666}';
let randomEmoji3 = '\u{1F999}';
let randomEmoji4 = '\u{1F333}';
let randomEmoji5 = '\u{1F222}';
console.log(randomEmoji1)
console.log(randomEmoji2)
console.log(randomEmoji3)
console.log(randomEmoji4)
console.log(randomEmoji5)
```

2024-05-31 07:43 UTC, git-Ball commented on Exercise02-Basics/Georgi-Balabanov/BASICS02-014.js
Fixed.

2024-05-31 07:45 UTC, git-Ball commented on Exercise03-DataTypes/Georgi-Balabanov/DTYPES01-003.js
> +console.log(fullRevName)
Fixed.

2024-05-31 15:23 UTC, karastoyanov approved these changes

2024-06-03 15:48 UTC, merged