second part of dtypes
karastoyanov/JSF-DIW pull request #46
Opened 2024-06-06 18:33 UTC by asenpetrov

second part of dtypes

2024-06-06 19:46 UTC, karastoyanov commented on Exercise03-DTypes/dtypes01-022.js
An example of solution without using if-else statements would be:

```js
let wordToCheck = "jump";
let pangram = "The quick brown fox jumps over the lazy dog";

let result = pangram.includes(wordToCheck) 
    ? `found at position: ${pangram.indexOf(wordToCheck)}` 
    : `does not exist.`;

console.log(result);    // found at position: 20
```

2024-06-06 19:48 UTC, karastoyanov commented on Exercise03-DTypes/dtypes01-023.js
An example of solution without using if-else statements would be:

```js
let wordToCheck = "jump";
let pangram = "The quick brown fox jumps over the lazy dog";

let result = pangram.includes(wordToCheck) 
    ? `found at position: ${pangram.indexOf(wordToCheck)}` 
    : `does not exist.`;

console.log(result);    // found at position: 20
```

2024-06-06 19:50 UTC, karastoyanov commented on Exercise03-DTypes/dtypes01-017.js
Missing solution. It would look like that:

```js
let num1 = "1";
let num2 = "10";
let num3 = "38";
let num4 = "4";
let num5 = "824";
let num6 = "120";
let num7 = "999";
let num8 = "64";

let modNum1 = ((num1.padStart(8, 0)).replaceAll(8, 9)).replaceAll(9, 1);
let modNum2 = ((num2.padStart(8, 0)).replaceAll(8, 9)).replaceAll(9, 1);
let modNum3 = ((num3.padStart(8, 0)).replaceAll(8, 9)).replaceAll(9, 1);
let modNum4 = ((num4.padStart(8, 0)).replaceAll(8, 9)).replaceAll(9, 1);
let modNum5 = ((num5.padStart(8, 0)).replaceAll(8, 9)).replaceAll(9, 1);
let modNum6 = ((num6.padStart(8, 0)).replaceAll(8, 9)).replaceAll(9, 1);
let modNum7 = ((num7.padStart(8, 0)).replaceAll(8, 9)).replaceAll(9, 1);
let modNum8 = ((num8.padStart(8, 0)).replaceAll(8, 9)).replaceAll(9, 1);

console.log(modNum1);
console.log(modNum2);
console.log(modNum3);
console.log(modNum4);
console.log(modNum5);
console.log(modNum6);
console.log(modNum7);
console.log(modNum8);
```

2024-06-06 19:50 UTC, asenpetrov commented on Exercise03-DTypes/dtypes01-022.js
thank you, Aleks, will try to rework it.

2024-06-06 19:51 UTC, karastoyanov requested changes
`Dtypes01-017`, `Dtypes01-022` and `Dtypes01-023` code review

2024-06-28 00:28 UTC, karastoyanov commented on Exercise06-Loops/loops-01-010.js
If you run the program with `0`, `1` or any negative number the result would be "Numbeer ... is primer".  A prime number is a number that can only be divided by itself and 1 without remainders, AND it's different than 0 or 1.

2024-06-28 00:29 UTC, karastoyanov requested changes
Loops-01-010 needs additional attention.

Will take a look on the task during the course, @ivaylochenchev

2024-07-11 19:05 UTC, karastoyanov approved these changes

2024-07-11 19:12 UTC, merged